#!/bin/bash
set -uex

main () (
  npm ci
  mkdir -p dist
  cp assets/* dist
  npm run bundle
  npm run minify-js

  npm run minify-css
  mv dist/prod-index.html dist/index.html
  rm -rf public
  mv dist public
  ./scripts/content-hash
  gzip -k -6 -r public
)

rename_file_with_content_hash () (
  file=$1
  hash="$(hash_content "$file")"
  new_file="$(echo -n "$file" | sed -En "s/^(.+)(\.[^.]+)"'$'"/\1-${hash}\2/p")"
  find="$(basename "$file")"
  replace="$(basename "$new_file")"
  cp "$file" "$new_file"

  sed -i "s|${find}|${replace}|" assets/{prod-,}index.html
)

hash_content () (
  file=$1
  checksum="$(cksum "$file" | awk '{ print $1 }')"

  # convert base10 input to base16 output
  bcprogram="ibase=10; obase=16; ${checksum}"

  echo "$bcprogram" \
    | bc \
    | xxd --revert --plain \
    | base64 \
    | tr '+' '-' \
    | tr '/' '_' \
    | tr -d '='
)

main

